### ISSUE TITLE
[CAL] Some pythonqt module ideas

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#106]
I created yeterday a mockup for a possible CAL selector widget.

[![cal_pyqt.png](https://s27.postimg.org/i85xbih5f/cal_pyqt.png)](https://postimg.org/image/41q6ga6a7/)

The widget would just set mirrorlocation, branch and mwhd driver(free/nonfree) in the globalstorage and rank mirrors.

Now the question, do we want to have a module which does these above tasks, or should mhwdcfg go pythonqt to implement the driver thingy?

Modules that can be enhanced to pythonqt:

- [ ] mhwdcfg
- [ ] postcfg
- [ ] chrootcfg
- [ ]  (new) mirrorcfg
- [ ] (new)  branchcfg

**Comment by udeved** [comment]
The mirrors are still some headache, since we don't reliably boot with fastest mirrors set.
Random mirrors is not sufficient for any netinstall.

**Comment by philmmanjaro** [comment]
Well, the mirrors are different in speed, depending on your location. To define that we might need some tests done by the community. For us, it doesn't matter much. German mirrors are fast and current also. So yes, it is an issue, however we should start on some point and make the installation process more visual. You can check with **Antergos** on how they might have solved it. However, the NetInstall media will have **bugs** and other **issues** the normal classic install medias might have not, since there we don't need to have a **mirror** online.

**Comment by udeved** [comment]
Hmm, I think a mirror selection is desirable, could be either reused from postcfg or dropped there, if we had a mirror module standalone.
As for netinstall, a branch selection would be nice, for chrootcfg, we could have indeed a stable iso, and user could select branch to be installed from.
mhwd could also use selection for free/nonfree.

Just some immediate modules we could use gui.
