### ISSUE TITLE
Booting up in VirtualBox not possible - i686 only

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#162]
Beginning with addition of the new **toolchain** it seems not to be possible to boot any **i686** ISO properly in **VirtualBox**, at least on my Ryzen system. Using [Boxes](https://wiki.gnome.org/Apps/Boxes) it works.

**Comment by oberon2007** [comment]
When you install **xorg** group you could simply check if any of the packages does not have the hint "reinstalling" during installation...?

**Comment by oberon2007** [comment]
My other guess is that it's really about restarting lightdm service in your scenario. Maybe during initial startup just something takes to long and then lightdm gets timed out.
What happens if you only restart the service without reinstalling anything?
Also if something wouldn't have been installed successfully in the first place you'd have to see an error in your buildlog.

**Comment by ThanosApostolou** [comment]
I did over 20 tests and my findings are these:

1. restarting lightdm doesn't work on it's own. Running **sudo pacman -Rnsc lightdm**, then **sudo pacman -S lightdm-gtk-greeter** and restarting lightdm doesn't work either.

2. Running **sudo pacman -S --needed xorg** on both i686 and x64 live images lists the same 48 packages, so there's no difference on installed packages from the group xorg.

3. However, installing the group **xorg** and then restarting lightdm solves the problem on i686!

That's really weird. Maybe some package is needed for i686 which is irrelevant on x64????

**Comment by oberon2007** [comment]
My question is still:
When you run `sudo pacman -S xorg`, do you see 
`warning: foo-xxx-x is up to date -- reinstalling` for each of the packages during installation?

**Comment by ThanosApostolou** [comment]
Yep same packages are installed and uninstalled on both i686 and x64:
![screenshot at 2017-06-22 17-03-39](https://user-images.githubusercontent.com/21288843/27438111-e6f7106e-576c-11e7-9cbf-8c0f1c6470de.png)

**Comment by ThanosApostolou** [comment]
Ok, I think I understood why this works.

`startx` gives this error:
![screenshot at 2017-06-22 17-06-32](https://user-images.githubusercontent.com/21288843/27438231-36c3b854-576d-11e7-8828-a796fdd04a08.png)

So, when I run `cat /var/log/Xorg.0.log`
I see this:
![screenshot at 2017-06-22 17-12-23](https://user-images.githubusercontent.com/21288843/27438476-09585d7e-576e-11e7-83e1-ab8fd2cf24f8.png)
So, if I understood correctly how this works, the problem is that module vboxvideo cannot be loaded but by installing the xorg group then it uses fbdev or vesa as alternatives solutions. So, we need to understand why vboxvideo module cannot be loaded.

**Comment by ThanosApostolou** [comment]
I see the same errors on x64 so that doesn't explain it either....

**Comment by ThanosApostolou** [comment]
Just to confirm, installing either **xf86-video-vesa** or **xf86-video-fbdev** fixes the problem (don't need to install them both).

So, maybe these packages should be included at live images, at least as a workaround for now. Later today or tomorrow I will try to build an ISO with those packages included only in the live session and try to do an installation on virtualbox to find out if those packages need to be included on the installed system as well or if they just affect live session.

**Comment by ThanosApostolou** [comment]
Sorry for "spamming" this, last comment and I leave it for you to figure this out :stuck_out_tongue: 

I compared the 17.0.2 and the 17.0.1 **Xorg.0.log**. After LoadModule fbdev and vesa fail (because the packages aren't included by default), then the problem seems to be at the kernel.

**17.0.2 error:**
![screenshot at 2017-06-22 19-16-52](https://user-images.githubusercontent.com/21288843/27444692-d2b4fa04-577f-11e7-860c-dd78f12e0ee9.png)

**17.0.1 booting fine:**
![screenshot at 2017-06-22 19-20-47](https://user-images.githubusercontent.com/21288843/27444724-ea8bd148-577f-11e7-8da9-5bd74337fbbf.png)

I believe the important difference is that in 17.0.1 we get: **using drv /dev/dri/card0**, while in 17.0.2 we get **open /dev/dri/card0: No such file or directory**. I lost too many hours trying to figure this out (and failing...) so now I leave it up to you :stuck_out_tongue:

**Comment by philmmanjaro** [comment]
Well, On **Boxes** it boots up just fine. So your theory with the **VirtualBox-Drivers** might be correct. Try to add **xdriver=vesa** to the grub menu and **mhwd** will install **vesa** on that session. This means, we simply remove the **virtualbox** drivers from the live-session on **i686** as **x86_64** is fine.

**Comment by ThanosApostolou** [comment]
Digging a bit more it seem to be related with... surprise surprise... **gcc7** again...

Trying to load vboxvideo module I saw these errors:
![screenshot at 2017-06-22 22-10-42](https://user-images.githubusercontent.com/21288843/27451472-ca995262-5797-11e7-9abd-4b4baddcefba.png)

Then I found this:
https://bugs.archlinux.org/task/54252
which leads to this:
https://www.virtualbox.org/ticket/16772#comment:8

So, yeah better not use at all vboxvideo for now because it might take several time to get fixed upstream.

**Comment by oberon2007** [comment]
Awesome! 🤣
Great research @ThanosApostolou , thank you!
So basically one would need to compile vbox 32bit with an older compiler version - which I guess will just not be possible to achieve, right @philmmanjaro ? Or is it? We love compiling vbox @philmmanjaro , don't we? 😆

**Comment by oberon2007** [comment]
Ah. In the arch bugreport there is a solution posted!
Basically we'd need to patch only the 32bit guest module for linux49...

**Comment by oberon2007** [comment]
At the bottom of the vbox link: 
> Fix is part of the most recent repository, also the latest available 5.1.x test builds have the fix. The changes are in r67293, r67294, r67295, r67296, r67297 and r67298. 

So we could theoretically build one of these snapshots already ...

**Comment by oberon2007** [comment]
If at all we want to go that route, I think 'fixing' the guest module with someones workaround is not a good idea, because then the ISOs might again conflict with vbox as soon as it gets updated with the official fix.
So I think the only clean way would be to use a newer vbox snapshot.

**Comment by oberon2007** [comment]
Something to consider also is maybe: For whom is the issue actually a problem? Well only for bleeding edge systems base on gcc7 - meaning just Archbased and probably something like Fedora ... ?

**Comment by ThanosApostolou** [comment]
Fedora 26 has indeed the same issue (I tried with it 2-3 days ago and I had the same problem). Tumbleweed does have a **vbox_fix_for_gcc7.patch** (https://build.opensuse.org/package/show/openSUSE%3AFactory/virtualbox) but I don't know if it's about this issue or maybe about something else.

@philmmanjaro better revert the latest commit (https://github.com/manjaro/iso-profiles/commit/e8b7840a69a5963c5e5ab47e3ec9a94935830b94) since it's better to solve it with a new virtualbox snapshot. If this hasn't been solved until the final release, then we just need to encourage people to use Boxes instead of virtualbox if they want to try the i686 image.

**Comment by oberon2007** [comment]
I will try building the latest [vbox testbuild-version](https://www.virtualbox.org/wiki/Testbuilds) - can't resist 😉 It will take a little while but later tonight I can say if that really fixes it, ok?

**Comment by Ste74** [comment]
But this suggest another question : how is important for us 32bit arch ?

**Comment by oberon2007** [comment]
although it will only fix it for Manjaro hosts of course ... ... 😜

**Comment by oberon2007** [comment]
Yes @Ste74 that's absolutely the question.
But I guess building vbox once until the next update arrives would be ok.

**Comment by philmmanjaro** [comment]
I added now the function to disable **VirtualBox** drivers if needed: https://github.com/manjaro/manjaro-tools/commit/965de2f5fc0c03661e970766883d3b887e51fd34

**Comment by oberon2007** [comment]
Working on the PKGBUILD for vbox svn version... I'll upload the 64bit package to someplace and let you know when it's ready.

**Comment by oberon2007** [comment]
Or would you like to build it on your  Ferrari maybe, @philmmanjaro ? In that case I'l just send you the PKGBUILD in a moment... 😉

**Comment by Ste74** [comment]
Not ferrari.. bmw m6 gt3 :D

**Comment by oberon2007** [comment]
chrchr never mind - I'm nearly done with svn checkout - that alone already takes forever ... 😆 then I can just let it run - given that the build works as expected 😉

**Comment by philmmanjaro** [comment]
@oberon2007: I've uploaded the ISOs now with **VB-drv** disabled on **i686**. As soon as we have the working version, we an switch back. The features is now added to **manjaro-tools**, so we may disable it again, when there is no fix or some broken. Seems gcc7 is again the key :smile:

**Comment by oberon2007** [comment]
we're just ahead of time... 😛

**Comment by philmmanjaro** [comment]
This is now [fixed](https://bugs.archlinux.org/task/54252#comment158744) and [committed](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170619/011880.html) to all branches :smile_cat:
