### ISSUE TITLE
[Manjaro32] Community Distribution of Manjaro in 32bit

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#174]
@jonathonf seems to want to keep the 32bit version of Manjaro still alive. Therefore I've created a new package called **boxit-32** with an additional **boxit-server** running on repo.manjaro.org. This results in a [lager footprint of Manjaro](https://lists.manjaro.org/pipermail/manjaro-mirrors/Week-of-Mon-20171113/000046.html).

```
du -h pool
2.2G	pool/overlay-32
54G	pool/sync
38G	pool/sync-32
4.1G	pool/overlay
97G	pool
```
Seems only few mirrors can handle this size change:

<img src="https://forum.manjaro.org/uploads/default/original/3X/9/1/91dc1710e18ab47cec56ef37bc35acd69eccf69a.jpg">

First step was to test the removal of **i686** packages in our **unstable** branch. The [current update](https://forum.manjaro.org/t/34695) did just that.

So these are the open points:

- [x] create a way to manage **Archlinux32** within **boxit**
- [x] reduce footprint of Manjaro
- [x] contact mirror hoster if there are still issues due changed footprint
- [x] decide which branches are needed for **Manjaro-32**. Suggested are at least `x32-stable x32-testing`
- [x] decide on how we manage our PKGBUILDs
- [x] decide if we want to have a **manjaro32** github organization to state it is a community project
- [x] decide who wants to be part of **Manjaro-32** developers/maintainer team
- [x] design **manjaro32.org homepage**. We could use the **github** page layout for a start :smile: 
- [ ] using **manjaro32.org domain** for github page ?!? [HowTo](https://help.github.com/articles/using-a-custom-domain-with-github-pages/).

**Comment by oberon2007** [comment]
How can the footprint be reduced? You mean by removing packages (of both architectures??) ?

**Comment by oberon2007** [comment]
I must say that I am not intending to invest a lot of energy in this branch of Manjaro.
Although I honor @jonathonf 's initiative, my position is that Manjaro has dropped 32bit support.

**Comment by philmmanjaro** [comment]
@oberon2007: footprint will be reduced when we finish the development cycle of the current **unstable** branch and snapping it to the other branches: Testing > Stable

**Comment by philmmanjaro** [comment]
I've updated the branches for now:

```
:: Available branches:

 1) stable
 2) testing
 3) unstable
 4) x32-testing
 5) x32-unstable
```

**Comment by oberon2007** [comment]
Ok. So that means with another stable update a x32-stable branch will be created?

**Comment by philmmanjaro** [comment]
I can't yet add a stable branch to the list. That will suggest that Manjaro-32 is tested and ready. It will come later if ever. For basic handling you need always minimum two branches. With **x32-unstable** we can sync from **Archlinux32** via **boxit-32** package. The renaming I've to do on the server itself. It depends at @jonathonf and the manjaro-32 team to do some out of it. I only gave them the infrastructure and basic management tool **boxit**.

**Comment by Ste74** [comment]
Only my 2 cents .. but how many people need this effort ? Always respect for @jonathonf effort but ... but...

**Comment by philmmanjaro** [comment]
@Ste74: I don't know either. We will see ...

**Comment by Huluti** [comment]
I find that it weighs down the project (whereas it should have been the opposite with the abandonment of 32-bits). It's a bit counterproductive and goes against Arch's philosophy. It's statistical, today very few people still use 32-bit. It's doomed to be abandoned. Let it die... It's many work for nothing at end...

**Comment by Chrysostomus** [comment]
Maybe it would be better to have a different approach with i686, since it is unsupported? Use arch32 repos directly, and only offer a single branch unstable repo for 32 manjaro packages?

Pro
- much less space usage
- possibly more mirrors therefore?
- less effort 

Con
- probably more unstable 
- arch kernels need to be put in the ignore list 
- probably problems with manjaro-mirrors because no branches
- using arch32 repos directly might necessitate rebuilding some manjaro packages more than if using snapshots? 
- is it even manjaro that way?

**Comment by philmmanjaro** [comment]
Well, I just invested some time to make this possible. This week we have some issues due this approach, since Manjaro-32 **v17.0.6** is still on our servers, at least in **stable** branch.

For now we have two **boxit-servers** running and therefore both projects, Archlinux and Archlinux32 hosted on our server as snapshot.

Manjaro uses the upstream packages as a snapshot and builds its own packages against it. The branches function is just an extra layer on our end and only two are needed to work as bare minimum: `stable testing`.

For now we have the new **Manjaro-32** additional on our server. With todays **unstable** update the **i686** packages got removed from that branch. When snapped over to **testing** and later to **stable** the official Manjaro only supports **x86_64** in `stable testing unstable`.

The new branches `x32-testing x32-unstable` hold Manjaro-32 for now. Having it this way, all our Mirrors will pick up both Projects. When splitting it up, it will has less infrastructure.

The Manjaro-Team and its community is for letting **i686** die. However some are still pro 32bit. Now we have to find a solution and how we may manage it without wasting too much time.

I'm willing to invest some time to give it a kick-start if needed. I will however stop supporting it at some point from my side.

**Comment by ThanosApostolou** [comment]
I agree with Philip's approach. It would be nice to provide the tools and see if there are enough volunteers to help jonathon's efforts to main x32 branches.

However, maybe there is any desire to further simplify buildpkg and buildiso tools by removing completely the 32bit options? If not, as long as those tools support 32bit (together with boxit-32), then all is good.

**Comment by philmmanjaro** [comment]
Removing **i686** support from our tools would make no sense to me. This would even make it harder for people willing to still support the 32bit architecture. Our team will focus on **x86_64** and Manjaro-32 will become their own Community Distro. For now it is close to the original Manjaro. We will see how fast Archlinux32 adopts some packages based on the status we have from the 08.11.17 in **x32-testing** branch.

**Comment by jonathonf** [comment]
[My intention](https://forum.manjaro.org/t/arch-linux-the-end-of-i686-support/34401/7?u=jonathon) with my [manjaro32 project](https://forum.manjaro.org/t/introducing-manjaro32-org/34634/?u=jonathon) was not to create more work - entirely the opposite, hence the lightweight approach to package management. My original direction was to build only those Manjaro-specific packages (kernels, modules, mhwd, etc.) against the current archlinux32 packages, therefore ending up with what's essentially an single-branch rolling release. The goal was that users would be able to migrate to using archlinux32, but retain the extra Manjaro goodness; essentially a sunsetting for existing 32-bit users, rather than a whole new distro.

If manjaro32 is to become more "official" this approach could change, but I'm wary of adding work if it's not needed. If you're saying that manjaro32 should become a fully-functioning three-branch 32-bit-only Manjaro, that's well beyond what I had in mind with my initial approach.

On the other hand, if 32-bit packages were to be maintained within Manjaro-proper, with regards boxit I'm not sure whether extra branches are necessary - I don't see why a sync can't take packages from two upstream sources, and once boxit has them in unstable then snapping from unstable->testing->stable would proceed as it has always done. However, having read through some of the boxit source code (C++, eww) I haven't yet identified the part where upstream packages are synchronised.

In either event, the main change would be with building the i686 Manjaro packages, which I've already got working with my Docker build container, so I can quite happily build away.

In terms of potential user-base, if we compare the [current download stats on Sourceforge](https://sourceforge.net/projects/manjarolinux/files/release/17.0.6/xfce/) for 17.0.6 Xfce, the 64-bit iso is currently at 15,460 downloads per week, i686 is at 2,545. It's smaller, but hardly insignificant.

**Comment by philmmanjaro** [comment]
@jonathonf: you don't find the repo set in the code. Here is a simple sync from **Archlinux32** with **boxit-32**:

```
boxit-32 sync
 host: repo.manjaro.org 
:: Connected to host repo.manjaro.org     
 username:
 password:
:: Available branches:

 1) stable
 2) testing
 3) unstable
 4) x32-testing
 5) x32-unstable

:: Branch index: 5
:: Current synchronization url: 'http://archlinux32.vollzornbrot.de/$arch/$repo'
   Change it? [y/N] 
:: Adjust exclude list? [y/N] 
:: Synchronizing branch 'x32-unstable'

:: Status

-------------------------------------------------------------------------------
                            BRANCH                                         JOB
-------------------------------------------------------------------------------
                      x32-unstable                      synchronizing packages

...


:: Status

-------------------------------------------------------------------------------
                            BRANCH                                         JOB
-------------------------------------------------------------------------------
                      x32-unstable                    finished synchronization

:: Synchronization successfully finished.
```

Why is boxit needed? 

* you can create a snapshot of Archlinux32 when ever you have time to do so
* you can define which packages you don't want to sync from Archlinux32 at all and make therefore your distro slick and small
* you can fully decide when a rebuild of your overlay packages are needed
* you can snap it over to the other x32-branch when you think your compilings are stable enough to be used by your community

I still suggest to go with a minimum of `x32-stable x32-testing` where you sync from Archlinux32 within `x32-testing` and snap the combined result when ready over to `x32-stable`. I just named them now `x32-testing x32-unstable` as not everything is ready yet.

I also will work on **boxit** a little more to remove official **Manjaro** branches from the list of **boxit-32** and wise versa ...

**Comment by philmmanjaro** [comment]
I've now **boxit-32** ready to be used. All current maintainers have the same access as with **boxit**. The following branches are currently available:

**boxit**

```
:: Available branches:

 1) stable
 2) testing
 3) unstable
```

**boxit-32**

```
:: Available branches:

 1) x32-testing
 2) x32-unstable
```
We are using the same infrastructure and most of our mirrors already adopted it. Also we have the same mailing lists for now. This we may split if needed. So from my side the new project has now the needed basic tools to start. I will add the needed boxit now also to **Manjaro-32**.

**Comment by fhdk** [comment]
diskstation> df -h manjaro
Filesystem         Size  Used Avail Use% Mounted on
/dev/vg1/volume_1  3.6T  817G  2.8T  23% /volume1

**Comment by jonathonf** [comment]
The new boxit-32 setup works really well, far better than my original overlay repo would.

I've updated the manjaro32.org placeholder homepage with up-to-date instructions and will move the site to a Jekyll-based design so it can be hosted on GitHub pages "soon"; I don't want to put too much effort in across too many aspects in case noone uses the i686 packages, in which case there's a good argument to drop the project entirely. At that point, people can't say we didn't try. ;)

**Comment by Strit** [comment]
How would you know how many people use it?

**Comment by jonathonf** [comment]
We should be able to gauge use through the "update announcement" forum posts, e.g. number of votes and replies. It won't be perfect but it will at least show it's in use.

**Comment by philmmanjaro** [comment]
@jonathonf: checkout https://manjaro32.github.io and see if that is already enough or you still want to change some with it.

**Comment by jonathonf** [comment]
Ah, that's a good start. I'll put this on my list for next week.

**Comment by fhdk** [comment]
My mirror footprint has actually shrunk :) - that's good news

```
diskstation> du -h .
2.8G	./pool/overlay
356.0K	./pool/sync/.~tmp~
36.5G	./pool/sync
2.7G	./pool/overlay-32
37.4G	./pool/sync-32
79.4G	./pool
51.7M	./stable/community/x86_64
51.7M	./stable/community
2.1M	./stable/core/x86_64
2.1M	./stable/core
22.3M	./stable/extra/x86_64
22.3M	./stable/extra
2.1M	./stable/multilib/x86_64
2.1M	./stable/multilib
78.2M	./stable
51.7M	./testing/community/x86_64
51.7M	./testing/community
2.1M	./testing/core/x86_64
2.1M	./testing/core
22.3M	./testing/extra/x86_64
22.3M	./testing/extra
2.1M	./testing/multilib/x86_64
2.1M	./testing/multilib
78.2M	./testing
51.6M	./unstable/community/x86_64
51.6M	./unstable/community
2.1M	./unstable/core/x86_64
2.1M	./unstable/core
22.3M	./unstable/extra/x86_64
22.3M	./unstable/extra
2.1M	./unstable/multilib/x86_64
2.1M	./unstable/multilib
78.1M	./unstable
58.3M	./x32-testing/community/i686
58.3M	./x32-testing/community
2.1M	./x32-testing/core/i686
2.1M	./x32-testing/core
26.2M	./x32-testing/extra/i686
26.2M	./x32-testing/extra
86.6M	./x32-testing
57.5M	./x32-unstable/community/i686
57.5M	./x32-unstable/community
1.8M	./x32-unstable/core/i686
1.8M	./x32-unstable/core
25.9M	./x32-unstable/extra/i686
25.9M	./x32-unstable/extra
85.3M	./x32-unstable
79.8G	.
```
@jonathonf @philmmanjaro 

I would like some input in the form of what are the goal for this change to `pacman-mirrors` to be able to recognize x32-config on a users machine. It is easy to check the architecture but how should pacman-mirrors get the info on x32 branch availability?

It would be very much preferred that the status of the x32 branches is included in the mirror-check-service and reflected in status.json.

I can add an architecture check to `pacman-mirrors` and internally prepend `x32-` to everything related to api, probing and mirror list writing.

The branches are - at present - not named but assuming knowledge of the serie in which they occur. A similiar approach could be thought of by adding a x32-branches to the config.json array of mirrors

Since a branch value of `-1` currently represents a unresponsive mirror I suggest using another indication whether a branch is available to x32 or not.

Pacman-mirrors translate 

    "branches": [ 1, 1, 0 ]

according to this tuple

    BRANCHES = ("stable", "testing", "unstable")

In the sample of one country I have used `-2, 1, 0` to indicate a non existing `stable` branch.

```
[
    {
        "branches": [ 1, 1, 1 ]
        "country": "Denmark",
        "las_sync": "02:39",
        "protocols": [
            "https"
        ],
        "url": "https://www.uex.dk/public/manjaro/"
        "x32-branches: [ -2, 1, 1 ]
    }
]
```

This approach would require minimal change to pacman-mirrors and keeping the usability for both architectures as the user would expect.

**Comment by philmmanjaro** [comment]
For repo.manjaro.org we have to ask @Huluti to add support for the 32bit repos. However we should split those. @fhdk: See it as a new project. For now you only see `stable testing unstable`. So if you say nothing needs to be changed and **i686** only has to modify them to `x32-stable x32-testing x32-unstable` with packaging, nothing has to be changed on your end. Those will be used in **Manjaro32** only.

**Comment by fhdk** [comment]
@philmmanjaro 
What I say is that pacman-mirrors is agnostic to a degree.

How it works now is that i686 is located next to x86_64 in the same branch.

How it look now the setup has split into separate structures which seems to be structural identical except for naming. For pacman-mirrors to recognize the difference it needs to differentiate by checking the machine architecture.

How do you plan to have pacman-mirrors differentiate without changes to pacman-mirrors codebase?

**Comment by philmmanjaro** [comment]
I simply only allow `x32-stable x32-testing x32-unstable` repos in **Manjaro32**, that´s all. Anything else needed?

**Comment by fhdk** [comment]
So - if I understand you correct - you will somehow translate the branch in the pacman-mirrors config to x32-stable?

You see the big picture - I obviously don't.

Today pacman know the difference between i686 and x86_64 and I suppose you could have pacman knowing where to find the branch for i686 architecture.

**Comment by philmmanjaro** [comment]
@jonathonf:

* Seems we have to patch **pacman-mirrors** to work for `x32-stable x32-testing x32-unstable` on **i686** architecture. This can be done with some [sed-magic on L39](https://github.com/manjaro/pacman-mirrors/blob/master/pacman_mirrors/config/configuration.py#L39). Can you give it a try on your end? 
* Then we might think about https://manjaro32.org adopting https://manjaro32.github.io homepage design. A [howto](https://help.github.com/articles/using-a-custom-domain-with-github-pages/) use the github pages is available.
* Last open point would be to know on how you use the PKGBUILDs. I assume the forks on [manjaro32](https://github.com/manjaro32) can be deleted.

**Comment by philmmanjaro** [comment]
Ok, **pacman-mirrors** works now also for **manjaro32** distro. Excellent. I assume we do our **PKGBUILD**s from the manjaro project, and therefore the clones in **manjaro32** project can be removed ... Is that the take we go for @jonathonf ?

**Comment by jonathonf** [comment]
Ideally - I don't really want to fork the project is at all possible. ;)

**Comment by philmmanjaro** [comment]
Ok, Makes sense. So I delete the repos then on the manjaro32 project as not needed.
