### ISSUE TITLE
Build chromium and mozilla app

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#188]
Continuing from [here](https://forum.manjaro.org/t/mozilla-and-google-api-keys-for-browsers-etc/42303)
and considering what happen now with manjaro-browser-settings ( no idea why pre hook not work in some situation ).
If the idea of @jonathonf is the future i think we can build now ( maybe only ff for now) and not invest more time to solve the issue. Let me know what think because for me the only workaround now is rebuild our ff how we rebuild before the introduction of hook into m-b-s.

@philmmanjaro @oberon2007 @Kirek @jonathonf ?

**Comment by philmmanjaro** [comment]
Maybe you create two hooks for each package. Having a joined hook might create the issue. However, I think the issue is in our repackaging. Since the ini is not known to pacman to be part of **firefox** or **firefox-developer-edition** it always complains. As soon as you have it installed once, pacman-db knows and it works. So we have to fix the first installation.

**Comment by philmmanjaro** [comment]
We have to split the hooks. This is why:

* currently the hook is creating the ini-files for both, **firefox** and **firefox-developer-edition**.
* when you try to additionally install the developer edition, **pacman** claims to already have the file and fails.
* we can only create the file after **firefox** or **firefox-developer-edition** got installed
* since we never had the ini-file for **firefox** package, we have to use **manjaro-settings** to remove the file, if possible.

**Comment by Ste74** [comment]
Ok, as comment in our forum let me try if over write instead of copy the ini file solve the issue.. When go home repack it and also yesterday read the pkgbuild  of ff and not remember correctly but Seem the api keys are stored in a file.. If is correct we can over write these..

**Comment by philmmanjaro** [comment]
I think I already fixed it hours ago ...

**Comment by Ste74** [comment]
See your commit before ;)
