### ISSUE TITLE
Release Community editions on the same day

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#29]
Since we have now more time to plan and schedule our time better I recommend to release all editions on the same day. Thoughts?

**Comment by excalibur1234** [comment]
that will be really hard to do. i can probably manage it, but probably not all maintainers will.

imho, the best way to release community editions is shortly after the "official editions". this requires manjaro-tools NOT to change within a certain time after the release of official editions.

for maintainers, it would be best to know (for example): "for 30 days after the release of official manjaro editions, manjaro-tools will not change. this is the time frame, i will not have any trouble with manjaro-tools. after that time frame might cause unexpected problems again."

**Comment by philmmanjaro** [comment]
We will have a freeze time within the development cycle. So with RC1 there will be no changes in our tools or profiles. Only bugfixing. So we will decide on **manjaro-tools** which features and updates are needed and develop them in our development cycle. 

This means beginning of May there should be no changes in that regard any more. So you guys can release some RCs to test the new **manjaro-tools** version. If you then find some issues still, we will discuss them and fix them before final release. What happend with **15.12** was just concentrating on our main releases but don't careing about **community editions**.

I still hope we will find a common ground here everybody can life with.

**Comment by Esclapion** [comment]
I think when ready, not "as it is", else we will release edition with known problems.

**Comment by philmmanjaro** [comment]
That's why I marked it as **optional** now. We will discuss this in a **development meeting** soon.

**Comment by oberon2007** [comment]
My thoughts: **Deepin** I would like to launch a new release as soon as two upstream bugfixes arrive. The reason is that since 15.12 a lot of development has happened and a new release will be a leap forward in quality and usability of this DE. Also my layout of the whole thing has evolved and I would be happy to present it soon ;) After that it should not be a problem from my PUV to publish an update release together with the next official release date.
**Cinnamon** is ready as a new release and btw now comes with this wonderful new **vertex-maia** gtk theme that should now also work for all other environments - this could also address the topic of meeting on a more or less common line with the design across releases. I will package the latest version of the theme today or tomorrow.
**i3** is a very well maintained release (and also very popular) and theoretically is (or was ;) ) ready to be re-release any time. It's design has changes since 15.12 and the new looks will be a lot closer to @Chrysostomus 's **bspwm** - so you could say that maybe also the looks of our tilers is joining :)
The work that **i3** (and I think bspwm, too) needs to have done is the necessary adjustments to the recent tools. The problems with different live-environment and custom **.bashrc** need to be solved. The only way I see around these problems atm is to either copy files in the chroot (ugly, but something I almost always have to do for my little pedantic details to be honest, anyway ;) )
My main concern for a unified release date is the amount of three releases I maintain.
To make that possible what needed to change is certainly that the release date should not be synchronized with stable updates, as it was recently.
If we could have the latest stable update on a Monday (or maybe even on Sunday) and then the release of the editions at the end of the week or at least a few days later, that would be a massive help for me ;)

**Comment by Chrysostomus** [comment]
When would the potential unified release commense? I can aim bspwm release to a certain date if I know where to aim. My original plan was to release next version somewhere near end of march, but I have no trouble delaying that.

**Comment by udeved** [comment]
I still propose to get community their own repo, and they can do what they want in that repo, and are not bound to release cycle.
Integrating doesn't really work, so we may come to realize the opposite direction can work.
We decouple community,and leave it entirely to community.
The WMs could do their thing in profiles,

I just don't want to jump through hoops constantly with some fringe WMs.

**Comment by Chrysostomus** [comment]
That makes sense, and would solve the bash issue to sufficient extent, at least for my purposes.

**Comment by udeved** [comment]
Oh, and community downloads should also have their own server or place, so no common upload of all iso to one place.
I personally wouldn't care if this new community repo would grew 1GB, it was a community issue then.

**Comment by philmmanjaro** [comment]
Sure. Then we split it also physically on our download projects. Makes sense.

**Comment by oberon2007** [comment]
I don't really see a reason for splitting repos.
Custom bash can easily be solved by moving **manjaro-base-skel** from Packages-Desktop to profiles Xfce and KDE.
The problem with different config in the live environment in my understanding is not a problem of profiles or desktop-settings but of **manjaro-tools** since the option to install overlay config in live has been removed. Or am I wrong?

**Comment by oberon2007** [comment]
And what's the idea of splitting download servers? I don't understand that, either, sorry...

**Comment by philmmanjaro** [comment]
Was just an idea. For now all is the way it is.

**Comment by udeved** [comment]
How about commuity get their own manjaro-release?

We have the problem, that community editions are being taken as newer if they are not in sync with official releases.
We need to address this somehow.
