### ISSUE TITLE
check if the upcoming GTK 3.20 will delay our release

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/release-plan#38]
Double check if we have to fix something due this

**Comment by Kirek** [comment]
Should we remove all gtk themes that haven't been updated in years form the repos? Build them with only gtk2 support maybe? Or just remove them.

**Comment by philmmanjaro** [comment]
@Kirek: it really depends. Do those old themes even work? See also #43

**Comment by philmmanjaro** [comment]
What is still needed for our KDE edition due this fact?

![manjaro-kde](https://cloud.githubusercontent.com/assets/5050022/14760980/36ef9924-0953-11e6-95a0-893e8ba34091.png)

**Comment by Kirek** [comment]
Nothing, the way that the kde edition configures gtk, it will now fallback to adwaita for gtk3. (until I re-add maia gtk3)
https://github.com/manjaro/manjaro-kde-settings/blob/master/etc/xdg/plasma-workspace/env/kde_gtk_config.manjaro.sh

**Comment by Ste74** [comment]
Our team is missing a graphic .. personally the easiest thing would be to remove all the old themes or broken .. as those who installed them receive updates from aur if you come or not? 
Otherwise you have to rebuild all with conflicts = ( 'GTK3'<3.20) ( for clean user install ) and remove the dependence?
