### ISSUE TITLE
Introduce pacman hooks?

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#39]
Shoud we introduce pacman hooks where it makes sense?

For example mhwd-gpu ca be nicely done with a post transaction hook, instead of calling it in several packages.

Another application would be manjaro-system replacement, so the sync first pacman patch became obsolete.

**Comment by udeved** [comment]
Some thought on practical implementation.

Alpm hooks would compile a given module at install, post transaction.

If we were to use this on install media, it would perhaps impact boot time negatively.
However, if we were to simply install all drivers,  the compilation would happen in chroot at iso build time.
Result was a fast boot, since no mhwd repo, but installers would need to tweaks.

**Comment by udeved** [comment]
> Required update to pacman-5.0.1 before 2016-04-23
> 
> 2016-03-24
> 
> The release of pacman-5.0 brought support for transactional hooks. These will allow us to (e.g.) run font cache updates a single time during an update rather than after each font package installation. This will both speed up the update process, but also reduce packaging burden for the Developers and Trusted Users.
> 
> In order for the use of hooks to be started, we require all users to have updated to at least pacman-5.0.1 before 2016-04-23. Pacman-5.0.1 was released on 2016-02-23, so this will have given everyone two months to update their system.

https://www.archlinux.org/

**Comment by philmmanjaro** [comment]
Hmm, we should think about how to smooth this....

**Comment by udeved** [comment]
I don't see how we could smooth this, if arch upstream start to switch using hooks.
We would need to build all packages ourselves, that use hooks.

Generally, I do think the alpm hooks are not a bad thing.

**Comment by udeved** [comment]
My thoughtis, if arch goes hooks, and all systems need to be updated anyway at a given date, it'd be ideal point to drop manjaro-system. We would not have to deal with old compatibility and such. 
Clean cut, it was.

**Comment by jonathonf** [comment]
With pacman 5 (default by 21st April) hooks are going to be the way forward.

**Comment by udeved** [comment]
I'd assume dkms will be triggered by a hook post transaction? Do you know @jonathonf ?

**Comment by Kirek** [comment]
This is no deadline, we just have to make sure that by 21st April all systems have pacman 5.0.1 or greater, or use manjaro-system to update pacman before anything else if it's lower than 5.0.1. We can change to hooks when we feel is right, .install scripts aren't going away.

**Comment by udeved** [comment]
I am more asking why we don't drop manjaro-system, if we have hooks available, that do the same thing, but can be better controlled. Should be doable to implement with 16.06.

The "deadline" would be simply good point to drop manjaro-system, and start using hooks that deal with manjaro specific upgrade solutions.

**Comment by udeved** [comment]
I started a very little library derived from mankaro-system here
https://github.com/udeved/manjaro-pacman-hooks/blob/master/lib/util-pacman.sh

**Comment by jristz** [comment]
As from arch I can take the next info.
* hooks are runing in the same order as udev will so, 10-algo.hoo first, then 20 then 30...
* pretransactional hooks will run before start intalling packages and postransactional after installing all, install files are just like always but they will privilege hooks to install files
* with the correct order using point 1 you can run dkms > mkinitcpio > grub-mkconfig without linux-headers problems
* arch still planing on how ship dependencies with hooks, so far a package that is need to run a hook will contain the hook (gtk-update-icon-cache /usr/share/libalpm/hooks/gtk-update-icon-cache.hook)
* there still proposals to add more hooks like some daemon-reload for systemd, since is just the Todo list show hooks part 1 is just the first part
* so the deadline just marc the start of hook migrating
* there not deadline for finish the hooks since they can be improbed
* you can call scripts from the hook

basically that all, fonts hook arent ready but nine system I have this.
70-dkms-install.hook           gtk-query-immodules-2.0.hook
70-dkms-remove.hook            gtk-query-immodules-3.0.hook
90-fc-cache-ib.hook            gtk-update-icon-cache.hook
gconf-install.hook             texinfo-install.hook
gconf-remove.hook              texinfo-remove.hook
gdk-pixbuf-query-loaders.hook  update-desktop-database.hook
gio-querymodules.hook          update-mime-database.hook
glib-compile-schemes.hook
so far, hope this will help you not get in the problem.

Also I think somone mention in the mailist that call pacman from a hook will trigger a infinite bucle/loop.
this repo have examples that so far with little modification and fw bugfixing has landed in the repo https://github.com/andrewgregory/pachooks there are some regresins compared with install files syntaxis in that repo but so far still usable as example.
