### ISSUE TITLE
Stuck at Starting Wait for Plymouth Boot Screen to quit

### ISSUE THREAD

**Issue by apolytos** [manjaro/release-plan#96]
My hardware: i5 7200u, intel hd 620 graphics, when I check graphics driver installed using mhwd -li it shows intel graphics is installed. How to solve this? And how can I disable mhwd altogether at boot?

**Comment by apolytos** [comment]
closed but what's the solution?

**Comment by WildOrangutan** [comment]
Same problem here while booting from USB. Tough I'm on desktop PC.

**Comment by philmmanjaro** [comment]
did you guys test **v17.0-rc3** yet?

**Comment by WildOrangutan** [comment]
Just tried KDE rc3 64 version. When I try to boot it, display goes black almost instantly. Tried with DP and DVI-D cable, no difference.

**Comment by WildOrangutan** [comment]
I'm just gonna write down my solution here, since this is most top google search hit, where I can actually comment...
I managed to get around my problems with following procedure. Also note that I have intel + nvidia so you may have to do smth differently.

1. Downloaded latest stable Manjaro release, v17 at this point
2. Boot from usb, with parameters: "nomodeset i915.modeset=0 nouveau.modeset=0" to bypass my black screen
3. Got stuck at Plymouth, hit Ctrl+Alt F2 and just installed nvidia drivers: "sudo mhwd -a pci nonfree 0300"
4. Entered "startx" command and desktop booted up successfully.
5. Installed Manjaro and didn't reboot yet
6. Repeat step 3.

**Comment by philmmanjaro** [comment]
**v17**-final doesn't use **plymouth** at all. We changed that with **rc3**.

**Comment by WildOrangutan** [comment]
Sorry about that, I messed it up...  At point 3. it got stuck at line "Started TLP system startup/shutdown"

**Comment by philmmanjaro** [comment]
If you search for it in the internet you may find a lot of it. Is it a hybrid solution on a laptop?
