### ISSUE TITLE
Xorg and catalyst into profiles

### ISSUE THREAD

**Issue by Ste74** [manjaro/release-plan#99]
@udeved , @Kirek , @oberon2007 : 
all profiles both in old repo and in the new iso-profiles need to disable the non free-driver to work properly .. for now i can disable in all profiles and rebuild the pkgs to do in boxit otherwise mt not work.. 
After need to decide if the non-free driver need to release in the install-media i think .

**Comment by Ste74** [comment]
This solution not work .. where mt call catalyst-input ? this file break the installation ..
https://forum.manjaro.org/t/manjaro-tools-0-13-8-5-iso-problem-after-boot/15993/23

**Comment by holmeslinux** [comment]
hi all
i have no catalyst-input input in Packages.* file
but it appears
for me, the use of mouse and touchpad do not work

vlw fwi, Holmes :)

**Comment by philmmanjaro** [comment]
I don't get the problem here. **[catalyst-input](https://github.com/manjaro/packages-extra/blob/master/catalyst-input/PKGBUILD)** and **[catalyst-video](https://github.com/manjaro/packages-extra/blob/master/catalyst-video/PKGBUILD)** include some drivers which might got removed by xorg-stack update to series v1.19. Please use **mt-0.14** and **iso-profiles**. Using **mt-0.13** might not be wise as we would need to adopt those changes. It would be great if you guys test [Beta2](https://sourceforge.net/projects/manjarotest/files/17.0-beta1/) on if you still have issues with **Catalyst**.

**Comment by Ste74** [comment]
I think this can be close :)
